import { alias } from '@ember/object/computed';
import { service } from '@ember/service';
import Controller from '@ember/controller';
import C from 'ui/utils/constants';
import ContainerSparkStats from 'ui/mixins/container-spark-stats';

export default Controller.extend(ContainerSparkStats, {
  prefs: service(),
  sparkInstances: alias('model.instances'),
  sortBy: 'name',
  liveSortFields: ['cpuRms', 'memoryRms', 'networkRms', 'storageRms'],
  statsPageSizes: C.TABLES.STATS_PAGE_SIZES,
  statsTablePreferenceKey: C.PREFS.STATS_TABLE_COUNT,
  statsColumnPreferenceKey: C.PREFS.SERVICE_CONTAINER_COLUMNS,

  headers: [
    {
      name: 'stateSort',
      columnKey: 'state',
      searchField: 'displayState',
      sort: ['stateSort', 'name', 'id'],
      translationKey: 'generic.state',
      columnRole: 'state',
      width: '112px',
    },
    {
      name: 'name',
      columnKey: 'name',
      sort: ['name', 'id'],
      translationKey: 'generic.name',
      columnRole: 'name',
    },
    {
      name: 'cpuRms',
      columnKey: 'cpu',
      sort: ['cpuRms', 'name', 'id'],
      translationKey: 'containersPage.table.cpuRms',
      columnRole: 'metric',
      defaultDescending: true,
      width: '120px',
    },
    {
      name: 'memoryRms',
      columnKey: 'ram',
      sort: ['memoryRms', 'name', 'id'],
      translationKey: 'containersPage.table.memoryRms',
      columnRole: 'metric',
      defaultDescending: true,
      width: '120px',
    },
    {
      name: 'networkRms',
      columnKey: 'network',
      sort: ['networkRms', 'name', 'id'],
      translationKey: 'containersPage.table.networkRms',
      columnRole: 'metric',
      defaultDescending: true,
      width: '120px',
    },
    {
      name: 'storageRms',
      columnKey: 'storage',
      sort: ['storageRms', 'name', 'id'],
      translationKey: 'containersPage.table.storageRms',
      columnRole: 'metric',
      defaultDescending: true,
      width: '120px',
    },
    {
      name: 'imageUuid',
      columnKey: 'image',
      searchField: 'displayImage',
      sort: ['imageUuid', 'name', 'id'],
      translationKey: 'containersPage.table.image',
      columnRole: 'image',
      defaultHidden: true,
    },
    {
      name: 'sortIp',
      columnKey: 'ip',
      searchField: 'displayIp',
      sort: ['sortIp', 'name', 'id'],
      translationKey: 'containersPage.table.ipAddress',
      columnRole: 'ip',
      width: '112px',
    },
    {
      name: 'primaryHost.displayName',
      columnKey: 'host',
      sort: ['primaryHost.displayName', 'name', 'id'],
      translationKey: 'servicePage.containersTab.table.header.host',
      columnRole: 'host',
    },
    {
      name: 'command',
      columnKey: 'command',
      searchField: 'command',
      sort: ['command', 'name', 'id'],
      translationKey: 'containersPage.table.command',
      columnRole: 'command',
      defaultHidden: true,
    },
    {
      isActions: true,
      columnKey: 'actions',
      columnRole: 'actions',
      width: '80px',
    },
  ],
});
